### ISSUE TITLE
bits-service-release does not show any releases

### ISSUE THREAD

**Issue by petergtz** [bosh-io/releases#26]
Hi,

On http://bosh.io/releases/github.com/cloudfoundry-incubator/bits-service-release?all=1 it says

> No versions available

although there is a valid bosh release on https://github.com/cloudfoundry-incubator/bits-service-release/releases/tag/1.4.0

Can you please help,

Thanks,
Peter and @suhlig

**Comment by cppforlife** [comment]
@petergtz havent yet re-ran pipeline script that creates new pipelines for added projects. (need a pipeline for that hehe)

**Comment by cppforlife** [comment]
should be up now: https://bosh.io/releases/github.com/cloudfoundry-incubator/bits-service-release?all=1
