### ISSUE TITLE
Hide concourse/concourse release

### ISSUE THREAD

**Issue by scottietremendous** [bosh-io/releases#78]
On bosh.io/releases, Concourse currently has two releases: 

- concourse/concourse
- concourse/concourse-bosh-release

This has created some confusion as concourse-bosh-release is the one that will be updated going forward. As a result we'd like to hide the concourse/concourse release. Please do not deprecate the release as we don't want existing manifests to break as a result.

**Comment by belinda-liu** [comment]
Hey @scottietremendous,

The link to the concourse/concourse release should be hidden from the releases page on bosh.io now. Folks can still navigate directly to the page via the url here: https://bosh.io/releases/github.com/concourse/concourse?all=1.

We're going to close this issue, feel free to reopen if this is still a problem.

Thanks!
@belinda-liu
